accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

dj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('auth/', include('accounts.urls')), # new
    path('auth/', include('django.contrib.auth.urls')), # new
    path('', include(('tasks.urls', "tasks"),namespace="tasks"))
]

tasks/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('new/', new, name="new"),
    path('delete/<int:pk>', delete, name="delete"),
    path('update/<int:pk>', update, name="update")
]

accounts/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

tasks/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from .models import Task
from django.contrib import messages

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    tasks = Task.objects.filter(author=request.user)
    context = {"tasks": tasks}
    return render(request, "tasks/index.html", context)

def new(request):
    name = request.GET.get('name', '')
    if name == '':
        messages.add_message(request, messages.INFO, 'Cannot create Empty Task')
    else:
        task = Task.objects.create(author=request.user, name=name)
    return redirect(reverse("tasks:index"))    

def delete(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    return redirect(reverse("tasks:index"))    

def update(request, pk):
    task = Task.objects.get(id=pk)
    if request.method == 'POST':
        name = request.POST.get('name','')
        if name == '':
            messages.add_message(request, messages.INFO, 'Cannot create Empty Task')
        else:
            task.name = name
            task.save()
        return redirect(reverse('tasks:index'))
    context = {"task": task}
    return render(request, "tasks/update.html", context)

tasks/templates/tasks/index.html
<a href="{% url 'logout' %}">Log out</a>
<form action="{% url 'tasks:new' %}">
    <input type="text" name="name" placeholder="New Task">
    <button type="submit">Create</button>
</form>
<ul>
    {%for task in tasks%}
        <li>
            {{task.name}} 
            <a href="{% url 'tasks:delete' task.id %}">Delete</a>
            <a href="{% url 'tasks:update' task.id %}">Update</a>
        </li>
    {%endfor%}
</ul>

tasks/templates/tasks/update.html
<form action="{% url 'tasks:update' task.id %}" method="post">
{%csrf_token%}
<textarea name="name" rows="10" cols="30">{{task.name}}</textarea>
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>